import * as vscode from 'vscode';
import * as path from 'path';
import { parsePostmanCollection, PostmanParseResult, PostmanRequest } from '../parser/postmanParser';
import { t } from '../util/i18n';

export function createImportPostmanCommand() {
  return async () => {
    // Step 1: Pick the Postman collection JSON file
    const fileUri = await vscode.window.showOpenDialog({
      title: t('importPostman.selectFile'),
      filters: { 'Postman Collection': ['json'] },
      canSelectMany: false,
    });

    if (!fileUri || fileUri.length === 0) return;

    // Step 2: Read and parse
    let parseResult: PostmanParseResult;
    try {
      const bytes = await vscode.workspace.fs.readFile(fileUri[0]);
      const content = new TextDecoder('utf8').decode(bytes);
      parseResult = parsePostmanCollection(content);
    } catch (err: any) {
      vscode.window.showErrorMessage(
        t('importPostman.parseError', { err: err.message || String(err) })
      );
      return;
    }

    if (parseResult.requests.length === 0) {
      vscode.window.showWarningMessage(t('importPostman.noRequests'));
      return;
    }

    // Step 3: Pick target folder
    const workspaceRoot = getWorkspaceRoot();
    let targetDir: string | undefined;

    // Suggest default locations for Spring projects
    const suggestedDirs = getSuggestedDirs(workspaceRoot);

    const dirChoice = await vscode.window.showQuickPick(
      [
        {
          label: suggestedDirs[0] || '$(folder) src/main/resources/',
          description: t('importPostman.defaultLocation'),
          target: suggestedDirs[0],
        },
        {
          label: '$(folder-open) ' + t('importPostman.chooseFolder'),
          description: '',
          target: null, // custom
        },
      ],
      { placeHolder: t('importPostman.pickTarget') }
    );

    if (!dirChoice) return;

    if (dirChoice.target === null) {
      const chosen = await vscode.window.showOpenDialog({
        title: t('importPostman.selectTarget'),
        canSelectFolders: true,
        canSelectFiles: false,
        canSelectMany: false,
        defaultUri: workspaceRoot,
      });
      if (!chosen || chosen.length === 0) return;
      targetDir = chosen[0].fsPath;
    } else {
      targetDir = dirChoice.target;
      // Ensure dir exists
      await vscode.workspace.fs.createDirectory(vscode.Uri.file(targetDir));
    }

    if (!targetDir) return;

    // Step 4: Generate .http file(s)
    const fileName = path.basename(fileUri[0].fsPath, '.json') + '.http';
    const outputPath = path.join(targetDir, fileName);

    const httpContent = renderHttpFile(parseResult);

    try {
      await vscode.workspace.fs.writeFile(
        vscode.Uri.file(outputPath),
        new TextEncoder().encode(httpContent)
      );
    } catch (err: any) {
      vscode.window.showErrorMessage(
        t('importPostman.writeError', { err: err.message || String(err) })
      );
      return;
    }

    // Step 5: Open the generated file
    const doc = await vscode.workspace.openTextDocument(vscode.Uri.file(outputPath));
    await vscode.window.showTextDocument(doc);

    // Done
    vscode.window.showInformationMessage(
      t('importPostman.success', {
        name: parseResult.collectionName,
        count: String(parseResult.requests.length),
        file: fileName,
      })
    );
  };
}

function renderHttpFile(parseResult: PostmanParseResult): string {
  const lines: string[] = [];

  // Header comment
  lines.push(`# Imported from Postman: ${parseResult.collectionName}`);
  lines.push(`# Generated by Spring HTTP Buddy on ${new Date().toISOString().slice(0, 10)}`);
  lines.push('');

  for (const req of parseResult.requests) {
    renderRequest(lines, req);
  }

  return lines.join('\n') + '\n';
}

function renderRequest(lines: string[], req: PostmanRequest): void {
  lines.push(`### ${req.name}`);
  lines.push(`${req.method} ${req.url}`);

  // Default headers
  const hasContentType = req.bodyContentType && req.body?.trim();
  const hasContentTypeHeader = req.headers.some(
    (h) => h.key.toLowerCase() === 'content-type'
  );

  if (hasContentType && !hasContentTypeHeader) {
    lines.push(`Content-Type: ${req.bodyContentType}`);
  }

  for (const h of req.headers) {
    lines.push(`${h.key}: ${h.value}`);
  }

  if (req.body?.trim()) {
    lines.push('');
    lines.push(req.body);
  }

  lines.push('');
}

function getWorkspaceRoot(): vscode.Uri | undefined {
  const folders = vscode.workspace.workspaceFolders;
  return folders?.[0]?.uri;
}

function getSuggestedDirs(workspaceRoot?: vscode.Uri): string[] {
  if (!workspaceRoot) return ['src/main/resources'];

  return [
    path.join(workspaceRoot.fsPath, 'src', 'main', 'resources'),
    workspaceRoot.fsPath,
  ];
}
